
    CREATE SCHEMA IF NOT EXISTS silver;

    CREATE TABLE IF NOT EXISTS silver.news (
                    "id" INTEGER,
                    "href" TEXT,
                    "published_at" TEXT,
                    "title" TEXT,
                    "description" TEXT,
                    "body" TEXT,
                    "language" TEXT,
                    "author" REAL,
                    "image" TEXT,
                    "categories" TEXT,
                    "topics" TEXT,
                    "industries" TEXT,
                    "entities" TEXT,
                    "summary" TEXT,
                    "keywords" TEXT,
                    "links" TEXT,
                    "media" TEXT,
                    "is_duplicate" INTEGER,
                    "is_free" INTEGER,
                    "is_breaking" INTEGER,
                    "read_time" INTEGER,
                    "sentences_count" INTEGER,
                    "paragraphs_count" INTEGER,
                    "words_count" INTEGER,
                    "characters_count" INTEGER,
                    "source.id" INTEGER,
                    "source.domain" TEXT,
                    "source.home_page_url" TEXT,
                    "source.type" TEXT,
                    "source.bias" TEXT,
                    "source.rankings.opr" INTEGER,
                    "source.location.country_name" TEXT,
                    "source.location.country_code" TEXT,
                    "source.favicon" TEXT,
                    "sentiment.overall.score" REAL,
                    "sentiment.overall.polarity" TEXT,
                    "sentiment.title.score" INTEGER,
                    "sentiment.title.polarity" TEXT,
                    "sentiment.body.score" REAL,
                    "sentiment.body.polarity" TEXT,
                    "story.id" INTEGER,
                    "story.uri" TEXT,
                    "author.id" REAL,
                    "author.name" TEXT
                );
    